project_id = "kfddlytvdzqwopongnew"

[functions.meta-conversions]
verify_jwt = false

[functions.hotmart-webhook]
verify_jwt = false

[functions.geo]
verify_jwt = false

[functions.visitor-tracking]
verify_jwt = false

[functions.elevenlabs-vsl]
verify_jwt = false

[functions.dashboard-events]
verify_jwt = false

[functions.vsl-background-music]
verify_jwt = false

[functions.vsl-sfx]
verify_jwt = false

[functions.download-vsl-audio]
verify_jwt = false